// One central manifest of every lead-magnet PDF, mapping the destination filename
// (in /public/downloads/) to the metadata the build needs.

export const LEAD_MAGNETS = [
  // Core
  { slug: 'home', file: 'uae-enterprise-ai-buyers-guide.pdf', title: "UAE Enterprise AI Buyer's Guide 2026", subtitle: '46 questions to ask any AI vendor before they touch your data.', sections: ['Procurement reality in the GCC', 'Sovereign deployment options', 'Model risk and governance', '46-question vendor checklist', 'Six-month implementation rhythm', 'Reference architectures'] },
  { slug: 'about', file: 'brocode-due-diligence-pack.pdf', title: 'Brocode Solutions Due Diligence Pack', subtitle: 'Everything a procurement committee needs to clear a vendor approval in one pass.', sections: ['Company overview & financials', 'Engineering org chart', 'Certifications: ISO 27001, SOC 2 Type II, ISO 42001', 'Sub-processor list', 'Insurance & contracting posture', 'Sample references and case studies'] },
  { slug: 'why-brocode', file: 'why-brocode-comparison-matrix.pdf', title: 'Why Brocode AI — Comparison Matrix', subtitle: 'How we stack up against Big-4, hyperscaler PSOs, offshore dev shops, and DIY.', sections: ['Six-axis comparison framework', 'Where we are the right fit', 'Where we explicitly are not', 'Engagement models and pricing bands', 'Three-customer reference call program'] },
  { slug: 'careers', file: 'brocode-compensation-relocation-guide.pdf', title: 'Compensation & Relocation Guide — Brocode AI', subtitle: 'Bands, benefits, and what relocation actually looks like in Abu Dhabi.', sections: ['Salary bands by role and seniority', 'Equity participation', 'Visa and dependent process', 'Schools, healthcare, housing', 'First 90 days in Abu Dhabi'] },
  { slug: 'contact', file: 'brocode-research-mode-onepager.pdf', title: 'Brocode AI — Research-Mode One-Pager', subtitle: 'A two-page institutional intro for procurement and investor research.', sections: ['Who we are', 'What we build', 'Where we operate', 'Selected references', 'Key contacts'] },

  // Services
  { slug: 'machine-learning-development', file: 'production-ml-readiness-audit.pdf', title: 'Production ML Readiness Audit (47 questions)', subtitle: 'A diagnostic for teams whose ML models keep slipping at the production gate.', sections: ['Data foundation readiness', 'Modelling discipline', 'MLOps backbone', 'Risk and governance', 'Operational support', 'Scoring rubric and benchmarks'] },
  { slug: 'deep-learning-solutions', file: 'applied-research-reproducibility-playbook.pdf', title: 'Applied Research Reproducibility Playbook', subtitle: 'How to keep a research-grade DL programme reproducible and audit-ready.', sections: ['Experiment tracking standards', 'Data and model lineage', 'GPU cluster economics', 'Reproducer kit standards', 'Publication and IP guidance'] },
  { slug: 'nlp', file: 'khaleeji-arabic-nlp-benchmark.pdf', title: 'Khaleeji Arabic NLP Benchmark 2026', subtitle: 'Open benchmark of 8 models on Gulf-dialect NER, classification, and summarisation.', sections: ['Dataset and corpus', 'Model comparison: AraBERT-v2, CAMeLBERT, Jais', 'Khaleeji vs MSA performance gaps', 'Cost per million tokens', 'Reproducer on GitHub'] },
  { slug: 'computer-vision', file: 'detection-benchmark-report.pdf', title: 'Industrial Vision Detection Benchmark', subtitle: 'YOLO / SAM / EfficientAD on UAE/KSA plant-floor defect data.', sections: ['Benchmark setup', 'mAP, recall, false-positive comparison', 'Edge inference latency (Jetson AGX Orin)', 'PROFINET / OPC UA integration patterns', 'Pre-contract free benchmark offer'] },
  { slug: 'generative-ai-development', file: 'pilot-to-production-tracker.pdf', title: 'GenAI Pilot-to-Production Tracker', subtitle: 'The 12-week path with named gates and exit criteria.', sections: ['Weeks 1-4: discovery and design', 'Weeks 5-8: hardened build', 'Weeks 9-12: regulator-ready evidence', 'Gates and exit criteria', 'Reference team and cost'] },
  { slug: 'llm-fine-tuning', file: 'gulfbench-v2-eval-pack.pdf', title: 'GulfBench v2 — LLM Fine-Tuning Evaluation Pack', subtitle: 'An open eval suite for Khaleeji-tuned LLMs with reproducer code.', sections: ['Benchmark methodology', 'Base model comparison (Mistral, Llama, Jais)', 'Fine-tuning recipes (QLoRA, DPO, ORPO)', 'Cost and latency at H100 / H200', 'Reproducer on GitHub'] },
  { slug: 'conversational-ai-chatbots', file: 'khaleeji-containment-benchmark.pdf', title: 'Contact-Centre Containment Benchmark — Khaleeji Arabic', subtitle: 'How AI assistants actually perform on Gulf-dialect calls and chats.', sections: ['Test setup: 200 calls, 1,000 chats', 'Containment, AHT, CSAT', 'Khaleeji vs MSA performance', 'Genesys / NICE / Avaya integration', 'Contractual deflection SLA model'] },
  { slug: 'ai-agents-agentic-workflows', file: 'exception-closure-audit.pdf', title: 'Exception-Closure Audit — RPA + Agents', subtitle: 'A 30-day audit of where your RPA estate is leaking work to humans.', sections: ['Audit methodology', 'Top 8 exception classes by cost', 'Agentic resolution patterns', 'Supervisor pattern (LangGraph + Temporal)', 'Sample exception-closure SLA'] },
  { slug: 'predictive-analytics', file: 'forecast-tournament.pdf', title: 'Demand Forecast Tournament — Free 3-Week Pilot', subtitle: 'We run six forecasting approaches on your data and publish the results.', sections: ['Tournament methodology', 'TimeGPT, Chronos, NeuralProphet, N-BEATSx, TFT, LightGBM', 'Holdout strategy', 'Acceptance criteria', 'Move to production path'] },
  { slug: 'recommendation-systems', file: 'cold-start-recsys-benchmark.pdf', title: 'Cold-Start Recommendation Systems Benchmark', subtitle: 'Two-tower retrieval, CLIP, contextual bandits on a regional catalogue.', sections: ['Test catalogue and baseline', 'Two-tower vs DeepFM vs DCN-v2', 'Multilingual CLIP + bge-m3 cold-start', 'Ramadan / Eid context embeddings', 'Triton + Vespa serving cost'] },
  { slug: 'speech-recognition-voice-ai', file: 'khaleeji-asr-wer-benchmark.pdf', title: 'Khaleeji ASR WER Benchmark', subtitle: 'Six engines on 50 hours of UAE and Saudi call audio.', sections: ['Benchmark setup', 'WER across dialects', 'Code-switching handling', 'Latency at 8k vs 16k', 'Free 200-call benchmark on your data'] },
  { slug: 'document-intelligence', file: 'arabic-ocr-benchmark-report.pdf', title: 'Arabic OCR Accuracy Benchmark — 7 Engines, 10,000 Documents', subtitle: 'How seven enterprise OCR engines perform on UAE government and banking Arabic.', sections: ['Benchmark setup', 'Field-level accuracy: ABBYY, Microsoft, Google, AWS, Brocode', 'Handwritten Arabic performance', 'TDRA-compliant on-prem appliance', 'Pre-contract free 500-document benchmark'] },
  { slug: 'mlops-ai-infrastructure', file: 'mlops-reference-architectures.pdf', title: 'MLOps Reference Architectures + TCO Calculator', subtitle: 'Four blueprints for AWS, Azure, on-prem, and hybrid — with cost models.', sections: ['Reference architecture 1: AWS SageMaker baseline', 'Reference architecture 2: Azure ML baseline', 'Reference architecture 3: on-prem (vLLM + MLflow + Ray)', 'Reference architecture 4: hybrid sovereign', 'TCO calculator (Google Sheet link)'] },
  { slug: 'self-hosted-llm-infrastructure', file: 'sovereign-llm-tco-pack.pdf', title: 'Sovereign LLM 36-month TCO Pack', subtitle: 'Hardware BoM, power, cooling, and licence for a customer-owned LLM appliance.', sections: ['Hardware BoM (8× H100 SXM5)', 'Power and cooling sizing', 'vLLM + Triton + TensorRT-LLM stack', '36-month TCO vs Azure OpenAI vs OpenAI Enterprise', 'Customer Thales / Entrust HSM patterns'] },
  { slug: 'ai-consulting-strategy', file: 'cxo-ai-playbook.pdf', title: 'CXO AI Playbook — Including a Sample Board Deck', subtitle: 'How to walk into the next board AI committee with an answer, not a question.', sections: ['Five-lens diagnostic', 'Value map and prioritisation', 'Sample board deck (redacted)', 'Six-month delivery rhythm', '8-week sprint contract template'] },
  { slug: 'ai-integration-services', file: 'integration-pattern-library.pdf', title: 'AI Integration Pattern Library — 12 Patterns', subtitle: 'How to embed AI into SAP, Oracle, mainframe, and core banking without ripping them out.', sections: ['Pattern 1: SAP via SAP IS + Kafka', 'Pattern 2: Oracle via OIC', 'Pattern 3: IBM i / AS400 via Boomi', 'Pattern 4: Mainframe z/OS via MQ', 'Patterns 5-12: core banking, claims, ERP, HRIS'] },
  { slug: 'intelligent-process-automation', file: 'rpa-ai-economics-pack.pdf', title: 'RPA + AI Economics Pack — 8 Processes', subtitle: 'Cost-per-transaction analysis for eight back-office processes.', sections: ['Invoice processing', 'KYC refresh', 'Claims triage', 'Procurement onboarding', 'HR exception handling', 'Payroll exception handling', 'Expense audit', 'Customer onboarding'] },
  { slug: 'data-engineering-for-ai', file: 'ai-ready-data-estate-diagnostic.pdf', title: 'AI-Ready Data Estate Diagnostic — 47 Points', subtitle: 'Self-score your data estate against what an AI programme actually needs.', sections: ['Source and ingestion', 'Modelling and transformation', 'Quality and contracts', 'Lineage and governance', 'Serving and feature stores', 'Scoring rubric (median GCC org: 41/100)'] },
  { slug: 'ai-model-optimization', file: 'model-optimisation-playbook.pdf', title: 'Model Optimisation Playbook — 4.2× Latency Reduction', subtitle: 'TensorRT, quantisation, distillation, ONNX runtime — when to use what.', sections: ['Pareto frontier methodology', 'Quantisation: INT8 / INT4 / FP4', 'Distillation playbook', 'Hardware targets: Jetson, Snapdragon, mobile, server', 'Public reproducer on GitHub'] },
  { slug: 'responsible-ai-governance', file: 'specimen-ai-risk-file.pdf', title: 'Specimen Regulator-Grade AI Risk File', subtitle: 'What the regulator wants to see — and what most teams ship.', sections: ['Model card', 'Datasheet for the dataset', 'Bias and fairness test pack', 'Explainability suite (SHAP, integrated gradients)', 'Controls mapping: ISO 42001, NIST AI RMF, EU AI Act, UAE AI Charter, SAMA, SR 11-7'] },

  // Industries
  { slug: 'government-public-sector', file: 'ai-procurement-playbook-federal.pdf', title: 'AI Procurement Playbook for UAE Federal Entities', subtitle: 'How to write an AI tender that actually gets you a working system.', sections: ['Tender structuring', 'Scoring criteria templates', 'Sovereign deployment evaluation', 'Vendor due-diligence checklist', 'Risk and audit clauses', 'Sample Statement of Work'] },
  { slug: 'banking-financial-services', file: 'model-risk-file-cbuae.pdf', title: 'Model Risk File for CBUAE-Supervised Banks', subtitle: 'A specimen evidence pack aligned to CBUAE expectations.', sections: ['Three-lines-of-defence operating model', 'AML / fraud / credit model evidence', 'Bias and fairness test pack', 'Model card and datasheet', 'Periodic validation playbook', 'CBUAE notification triggers'] },
  { slug: 'healthcare', file: 'clinical-ai-adoption-playbook.pdf', title: 'Clinical AI Adoption Playbook for JCI Hospitals', subtitle: 'From DOH/MOHAP/DHA approvals to clinician trust.', sections: ['Regulatory pathway (DOH, MOHAP, DHA)', 'Malaffi / NABIDH integration patterns', 'HL7 FHIR pipelines', 'MONAI medical imaging stack', 'Clinician change-management', 'Sample IRB submission'] },
  { slug: 'retail-ecommerce', file: 'ramadan-eid-forecasting-playbook.pdf', title: 'Ramadan & Eid Demand Forecasting Playbook', subtitle: 'How to model the seasonality the textbooks miss.', sections: ['Ramadan and Eid effects on demand', 'Multi-event embeddings', 'School-year, payday, weather features', 'Promo-aware uplift modelling', 'Inventory optimiser sizing', 'A/B testing in seasonal windows'] },
  { slug: 'manufacturing', file: 'plant-floor-ai-scaling-playbook.pdf', title: 'Plant-Floor AI Scaling Playbook', subtitle: 'From a single line to a multi-plant estate without losing OT control.', sections: ['Edge-to-cloud architecture', 'OPC UA / PROFINET / Ethernet/IP', 'CV-QA scaling patterns', 'Predictive maintenance economics', 'OT security posture (IEC 62443)', 'ICV / MoIAT alignment'] },
  { slug: 'real-estate-proptech', file: 'dubai-off-plan-valuation-report.pdf', title: 'Dubai Off-Plan Valuation Accuracy Report', subtitle: 'How well our valuation models predict actual transfer prices.', sections: ['Benchmark dataset (RERA / DLD / ADREC)', 'Model comparison', 'Off-plan vs ready market', 'Sub-community granularity', 'Confidence intervals', 'Sample valuation API'] },
  { slug: 'energy-utilities', file: 'refining-upstream-ai-field-guide.pdf', title: 'Refining & Upstream AI Field Guide', subtitle: 'Predictive maintenance, drilling, and methane analytics in ADNOC-grade ops.', sections: ['OSIsoft PI integration', 'AVEVA APC patterns', 'Petrel / OpenWorks workflows', 'Methane (OGMP 2.0) analytics', 'Refinery yield optimisation', 'Sample field-deployment runbook'] },
  { slug: 'logistics-supply-chain', file: 'gcc-cross-border-logistics-playbook.pdf', title: 'GCC Cross-Border Logistics AI Playbook', subtitle: 'Customs, port, last-mile, and lane optimisation across the region.', sections: ['Mirsal 2 / FASAH / Bayan integration', 'Navis N4 TOS connectors', 'Cross-border routing optimisation', 'Last-mile cost models', 'Fraud and document anomaly detection', 'Sample tender response'] },
  { slug: 'education', file: 'arabic-adaptive-learning-field-guide.pdf', title: 'Arabic Adaptive Learning Field Guide', subtitle: 'How to build Khaleeji-aware adaptive learning that ADEK and MoE will accept.', sections: ['Curriculum-aligned content generation (Jais + AraBERT-v2)', 'LTI 1.3 / xAPI integration', 'Early-warning systems for student success', 'UAE PDPL alignment', 'Sample pilot design', 'MBZUAI co-research framework'] },
  { slug: 'hospitality-tourism', file: 'gcc-hospitality-demand-playbook.pdf', title: 'GCC Hospitality Demand Playbook', subtitle: 'Pricing and intelligence for Ramadan, Hajj, Dubai Shopping Festival and beyond.', sections: ['Demand drivers in the GCC calendar', 'Opera Cloud / Mews integration', 'IDeaS / Duetto coexistence patterns', 'Multilingual concierge (Khaleeji, Russian, Mandarin)', 'F&B analytics', 'Loyalty intelligence'] },

  // Technology
  { slug: 'our-technology-stack', file: 'stack-2026-reference-architecture.pdf', title: '2026 Reference Architecture Pack', subtitle: 'Pinned versions of the stack we run in production today.', sections: ['Core ML: Python 3.11, PyTorch 2.4, vLLM 0.6, Ray 2.30', 'Platform: K8s 1.30, Terraform 1.9, Argo CD', 'Data: dbt, Airflow / Dagster, Iceberg, pgvector', 'Observability: MLflow 2.16, Arize, OpenLineage', 'Guardrails: NeMo Guardrails, Lakera Guard', 'Why we picked each (and what we rejected)'] },
  { slug: 'ai-platform-partners', file: 'partnership-dossier.pdf', title: 'Brocode AI Partnership Dossier', subtitle: 'Eight named partnerships and what each unlocks for your roadmap.', sections: ['NVIDIA Inception Premier', 'Microsoft AI Cloud Partner', 'AWS Advanced Tier', 'Hugging Face Enterprise', 'Anthropic Solution Provider', 'Databricks Lakehouse Partner', 'MBZUAI collaboration', 'TII collaboration'] },
  { slug: 'cloud-infrastructure-partners', file: 'uae-sovereign-hybrid-cloud-atlas.pdf', title: 'UAE Sovereign & Hybrid Cloud Atlas', subtitle: 'Seven UAE-resident cloud estates and where each fits.', sections: ['AWS UAE North', 'Azure UAE North', 'OCI Abu Dhabi', 'G42 Cloud', 'Khazna', 'du Cloud', 'e& Cloud', 'When to pick which'] },
  { slug: 'open-source-contributions', file: 'open-source-report-2026.pdf', title: 'Brocode AI Open-Source Report 2026', subtitle: 'What we ship to GitHub, and what we use in production.', sections: ['Khaleeji Benchmark (open dataset)', 'Arabic NLP datasets', 'vLLM contributions', 'tokenizers contributions', 'pgvector contributions', 'Internal tools we open-sourced'] },
  { slug: 'development-methodology', file: 'pmo-pack.pdf', title: 'PMO Pack — 22 Templates for AI Delivery', subtitle: 'Gates, RACI, evidence packs, and risk registers.', sections: ['G0–G3 gate definitions', 'Sprint plan templates', 'Model risk register', 'Regulator evidence pack', 'Sample steering deck', 'Sample retrospective format'] },
  { slug: 'quality-assurance-for-ai', file: 'audit-evidence-bundle.pdf', title: '2026 Audit-Evidence Bundle for AI', subtitle: 'A specimen evidence pack mapped to CBUAE, FSRA, NCA, and ISO 42001.', sections: ['Evaluation harness', 'Regression suite', 'Bias and fairness pack (Fairlearn, AIF360)', 'Drift detector pattern', 'Red-team and adversarial', 'Mapping to controls'] },

  // Insights
  { slug: 'whitepapers', file: 'gcc-enterprise-ai-benchmark-2026.pdf', title: 'GCC Enterprise AI Benchmark 2026', subtitle: '218-respondent primary survey of GCC enterprise AI maturity.', sections: ['Methodology and sample', 'AI roadmap maturity', 'Production AI rate (only 14%)', 'Sovereign deployment posture', 'Buying patterns', 'Sector benchmarks'] },
  { slug: 'guides', file: 'practitioner-pack-q1-2026.pdf', title: 'Practitioner Pack — Q1 2026 Bundle', subtitle: 'Three long-form guides for senior ML/AI practitioners.', sections: ['Arabic NLP at production scale', 'RAG that survives the regulator', 'MLOps for sovereign-cloud deployments'] },
  { slug: 'glossary', file: 'brocode-ai-glossary-pocket-guide.pdf', title: 'Brocode AI Glossary — Pocket Guide', subtitle: '240 terms a non-technical leader actually needs to know.', sections: ['Foundations', 'Models and architectures', 'Data and infrastructure', 'Governance and risk', 'GCC-specific terms (Arabic-script terms with parity)'] },
  { slug: 'faqs', file: 'procurement-pack.pdf', title: 'Procurement Pack — Brocode AI', subtitle: 'Pricing bands, IP clauses, exit-clause samples — what we share at first call.', sections: ['Pricing bands and engagement types', 'IP ownership and licensing', 'Exit and handover clauses', 'Security and compliance summary', 'Sample MSA and DPA', 'Reference call programme'] },
  { slug: 'insights-hub', file: 'insights-sampler.pdf', title: 'Brocode AI Insights Sampler', subtitle: 'Six representative pieces from across the hub.', sections: ['Whitepapers sampler', 'Guides sampler', 'Case study summary', 'Glossary sampler', 'FAQ excerpts', 'Newsletter sample'] },

  // Legal
  { slug: 'security-compliance', file: 'vendor-security-pack.pdf', title: 'Brocode Solutions Vendor Security Pack', subtitle: 'SOC 2 Type II + ISO 27001 SOA + DPA + sub-processor register.', sections: ['ISO 27001 Statement of Applicability', 'SOC 2 Type II report (NDA-gated)', 'ISO 42001 attestation', 'Sub-processor register', 'DPA template (UAE PDPL + GDPR aligned)', 'Incident response posture'] },
  { slug: 'privacy-policy', file: 'brocode-dpa-template.pdf', title: 'Brocode Data Processing Agreement Template', subtitle: 'UAE PDPL + GDPR + DIFC DP Law aligned, EU SCCs pre-filled.', sections: ['Roles and processing', 'Sub-processors', 'Security measures (Annex II)', 'Transfer mechanisms (SCCs 2021/914)', 'Audit rights', 'Term and termination'] },
  { slug: 'terms-of-service', file: 'brocode-msa-template.pdf', title: 'Brocode Master Services Agreement Template', subtitle: 'DIFC law or English law variant, with one-page Commercial Terms Summary.', sections: ['Commercial terms summary', 'Definitions', 'IP and licensing', 'Liability and warranties', 'Termination', 'Governing law (DIFC / English)'] },
  { slug: 'cookie-policy', file: 'cookie-audit-report.pdf', title: 'Brocode Website Cookie Audit Report', subtitle: 'Live audit of every cookie set by brocode.ae, refreshed quarterly.', sections: ['Cookie categories', 'Cookie register (live)', 'Third-party providers', 'GPC handling posture', 'Consent UX', '12-month changelog'] }
];
